using FormStart;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Windows.Forms;

namespace ZakatCalc
{
    public partial class ucDonations : UserControl
    {
        private DataAccess Da { get; set; }
        private ucCalculator calc { get; set; }
        private FormAdmin Fa;
        private FormDonor Fd;
        decimal amount;
        private int userID;

        public ucDonations()
        {
            InitializeComponent();
            try
            {
                Da = new DataAccess();
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
            }
        }

        public ucDonations(decimal amount, int userID, FormAdmin admin = null, FormDonor donor = null)
        {
            InitializeComponent();
            try
            {
                Da = new DataAccess();
                this.amount = amount;
                this.userID = userID;

                if (admin != null) { Fa = admin; }
                if (donor != null) { Fd = donor; }
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
            }
        }

        private void tnCancel_Click(object sender, EventArgs e)
        {
            try
            {
                if (Fa != null) { Fa.LoadControl(new ucCalculator("admin", userID)); }
                else if (Fd != null) { Fd.LoadControl(new ucCalculator("donor", userID)); }
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
            }
        }

        private void btnConfirm_Click(object sender, EventArgs e)
        {
            if (cbPayment.SelectedItem == null || string.IsNullOrEmpty(txtAmount.Text) || Convert.ToDecimal(txtAmount.Text) <= 0)
            {
                MessageBox.Show("Please select a payment method and enter a valid amount.");
                return;
            }

            try
            {
                decimal amount = Convert.ToDecimal(txtAmount.Text);
                string method = cbPayment.SelectedItem.ToString();
                string trnxID = txtTrnxID.Text.ToString();

                // Appended SELECT SCOPE_IDENTITY() to get the new donation_id
                string query = "INSERT INTO DONATIONS (user_id, total_amount, payment_method, transaction_ref) VALUES (" + this.userID + ", " + amount + ", '" + method + "', '" + trnxID + "'); " +
                               "SELECT SCOPE_IDENTITY();";

                // returns the new donation_id generated by the database
                object result = Da.ExecuteScalar(query);
                int newDonationId = Convert.ToInt32(result);

                trnxID = "ZKT-" + newDonationId.ToString().PadLeft(6, '0');

                if (newDonationId > 0)
                {
                    txtAmount.Clear();
                    cbPayment.SelectedIndex = -1;
                    txtTrnxID.Clear();

                    MessageBox.Show("Donation recorded successfully!");

                    if (this.FindForm() is FormAdmin parentForm)
                    {
                        var OrganizationSplit = new ucOrganizationSplit(parentForm, null, newDonationId, amount, trnxID);
                        parentForm.LoadControl(OrganizationSplit);
                    }
                    else if (this.FindForm() is FormDonor parentForm2)
                    {
                        var OrganizationSplit = new ucOrganizationSplit(null, parentForm2, newDonationId, amount, trnxID);
                        parentForm2.LoadControl(OrganizationSplit);
                    }
                }
                else
                {
                    MessageBox.Show("An error occurred while recording the donation. Please try again.");
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
            }
        }

        private void ucDonations_Load(object sender, EventArgs e)
        {
            try
            {
                txtAmount.Text = amount.ToString();
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
            }
        }

        private void txtTrnxID_TextChanged(object sender, EventArgs e)
        {
        }
    }
}